version: "3.9"

services:

  postgres:
    image: postgres:16

    container_name: resumeguide_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_analyzer

    ports:
      - "5432:5432"

    volumes:
        - resumeguide_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: resumeguide_backend

    restart: always

    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: 262231660312-iuf5hh93pfrb3l2c4oggr3rsf48n6j6d.apps.googleusercontent.com

    container_name: resumeguide_frontend

    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - backend

volumes:
  resumeguide_postgres_data: