import { DashboardData } from '@/types/dashboard';

export const mockDashboardData: DashboardData = {
  user: {
    name: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1234567?v=4',
  },
  scores: {
    resumeHealth: 87,
    careerReadiness: 78,
    marketCompetitiveness: 82,
  },
  scoreTrends: {
    resumeHealth: 'up',
    careerReadiness: 'up',
    marketCompetitiveness: 'stable',
  },
  aiCoachInsights: {
    advice:
      'Your resume is in great shape! Focus on quantifying your impact with specific metrics in your recent projects.',
    nextLearningStep:
      'Complete AWS Solutions Architect certification to unlock senior-level opportunities.',
    weeklyFocus:
      'Update 2-3 project descriptions with measurable business impact statements.',
    improvements: [
      'Added 8 new technical skills',
      'Improved ATS score by 12%',
      'Increased career readiness by 15%',
    ],
  },
  resumeVersions: [
    {
      id: '1',
      uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      fileName: 'resume_v5.pdf',
      scores: {
        resumeHealth: 87,
        careerReadiness: 78,
        marketCompetitiveness: 82,
      },
      skillChanges: {
        added: ['AWS', 'Docker', 'Kubernetes'],
        improved: ['React', 'TypeScript', 'System Design'],
      },
    },
    {
      id: '2',
      uploadedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      fileName: 'resume_v4.pdf',
      scores: {
        resumeHealth: 75,
        careerReadiness: 63,
        marketCompetitiveness: 78,
      },
      skillChanges: {
        added: ['Node.js', 'PostgreSQL'],
        improved: ['JavaScript'],
      },
    },
    {
      id: '3',
      uploadedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
      fileName: 'resume_v3.pdf',
      scores: {
        resumeHealth: 65,
        careerReadiness: 52,
        marketCompetitiveness: 68,
      },
      skillChanges: {
        added: ['Python'],
        improved: [],
      },
    },
  ],
  trendData: [
    { date: '1 week ago', resumeHealth: 79, careerReadiness: 68, marketCompetitiveness: 80 },
    { date: '2 weeks ago', resumeHealth: 81, careerReadiness: 72, marketCompetitiveness: 81 },
    { date: '3 weeks ago', resumeHealth: 83, careerReadiness: 75, marketCompetitiveness: 82 },
    { date: '1 month ago', resumeHealth: 75, careerReadiness: 63, marketCompetitiveness: 78 },
    { date: '6 weeks ago', resumeHealth: 72, careerReadiness: 60, marketCompetitiveness: 75 },
    { date: '2 months ago', resumeHealth: 68, careerReadiness: 55, marketCompetitiveness: 70 },
    { date: '3 months ago', resumeHealth: 65, careerReadiness: 52, marketCompetitiveness: 68 },
  ],
  skillMatrix: {
    strengths: [
      { name: 'React', level: 95, category: 'Frontend', yearsOfExperience: 5 },
      { name: 'TypeScript', level: 90, category: 'Language', yearsOfExperience: 4 },
      { name: 'System Design', level: 88, category: 'Backend', yearsOfExperience: 5 },
      { name: 'JavaScript', level: 92, category: 'Language', yearsOfExperience: 7 },
    ],
    weaknesses: [
      { name: 'Mobile Development', level: 35, category: 'Frontend' },
      { name: 'DevOps', level: 40, category: 'Infrastructure' },
      { name: 'Data Science', level: 30, category: 'Analytics' },
    ],
    missingSkills: [
      { name: 'AWS Solutions Architect', level: 0, category: 'Cloud' },
      { name: 'Kubernetes', level: 0, category: 'Infrastructure' },
      { name: 'Machine Learning', level: 0, category: 'Analytics' },
    ],
    learningPriorities: [
      { name: 'AWS', level: 45, category: 'Cloud' },
      { name: 'Docker', level: 50, category: 'Infrastructure' },
      { name: 'Terraform', level: 40, category: 'Infrastructure' },
      { name: 'Go', level: 35, category: 'Language' },
    ],
  },
  industryBenchmarks: [
    {
      metric: 'Resume Health Score',
      userScore: 87,
      marketAverage: 72,
      percentile: 85,
      trend: 'up',
    },
    {
      metric: 'Career Readiness',
      userScore: 78,
      marketAverage: 68,
      percentile: 78,
      trend: 'up',
    },
    {
      metric: 'Market Competitiveness',
      userScore: 82,
      marketAverage: 75,
      percentile: 82,
      trend: 'stable',
    },
  ],
  jobReadiness: [
    {
      category: 'ready',
      label: 'Ready to Apply',
      description: '4 senior roles you can apply for now',
      roles: [
        {
          id: '1',
          title: 'Senior Frontend Engineer',
          company: 'Tech Company A',
          matchPercentage: 95,
          category: 'ready',
          requiredSkills: ['React', 'TypeScript', 'System Design'],
          skillGaps: [],
          salary: { min: 150000, max: 180000 },
        },
        {
          id: '2',
          title: 'Staff Engineer',
          company: 'Tech Company B',
          matchPercentage: 92,
          category: 'ready',
          requiredSkills: ['System Design', 'Architecture', 'Leadership'],
          skillGaps: [],
          salary: { min: 200000, max: 250000 },
        },
        {
          id: '3',
          title: 'Lead Developer',
          company: 'Tech Company C',
          matchPercentage: 88,
          category: 'ready',
          requiredSkills: ['React', 'Node.js', 'Team Leadership'],
          skillGaps: [],
          salary: { min: 160000, max: 190000 },
        },
        {
          id: '4',
          title: 'Principal Engineer',
          company: 'Tech Company D',
          matchPercentage: 85,
          category: 'ready',
          requiredSkills: ['System Design', 'Architecture', 'Strategic Planning'],
          skillGaps: [],
          salary: { min: 220000, max: 280000 },
        },
      ],
    },
    {
      category: 'nearlyReady',
      label: 'Nearly Ready',
      description: '6 roles you could be ready for in 2-3 months',
      roles: [
        {
          id: '5',
          title: 'DevOps Engineer',
          company: 'Tech Company E',
          matchPercentage: 72,
          category: 'nearlyReady',
          requiredSkills: ['Kubernetes', 'AWS', 'Docker', 'Terraform'],
          skillGaps: ['Kubernetes', 'AWS'],
          estimatedMonthsToReady: 3,
          salary: { min: 140000, max: 170000 },
        },
        {
          id: '6',
          title: 'Full Stack Engineer',
          company: 'Tech Company F',
          matchPercentage: 68,
          category: 'nearlyReady',
          requiredSkills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
          skillGaps: ['AWS'],
          estimatedMonthsToReady: 2,
          salary: { min: 130000, max: 160000 },
        },
        {
          id: '7',
          title: 'Platform Engineer',
          company: 'Tech Company G',
          matchPercentage: 65,
          category: 'nearlyReady',
          requiredSkills: ['Kubernetes', 'Go', 'Docker', 'System Design'],
          skillGaps: ['Kubernetes', 'Go'],
          estimatedMonthsToReady: 4,
          salary: { min: 150000, max: 180000 },
        },
        {
          id: '8',
          title: 'Backend Lead',
          company: 'Tech Company H',
          matchPercentage: 70,
          category: 'nearlyReady',
          requiredSkills: ['Node.js', 'PostgreSQL', 'System Design', 'Team Leadership'],
          skillGaps: [],
          estimatedMonthsToReady: 1,
          salary: { min: 155000, max: 185000 },
        },
        {
          id: '9',
          title: 'Infrastructure Engineer',
          company: 'Tech Company I',
          matchPercentage: 62,
          category: 'nearlyReady',
          requiredSkills: ['Terraform', 'AWS', 'Kubernetes', 'Monitoring'],
          skillGaps: ['Terraform', 'AWS', 'Monitoring'],
          estimatedMonthsToReady: 4,
          salary: { min: 145000, max: 175000 },
        },
        {
          id: '10',
          title: 'Solutions Architect',
          company: 'Tech Company J',
          matchPercentage: 75,
          category: 'nearlyReady',
          requiredSkills: ['System Design', 'AWS', 'Architecture', 'Communication'],
          skillGaps: ['AWS'],
          estimatedMonthsToReady: 2,
          salary: { min: 170000, max: 210000 },
        },
      ],
    },
    {
      category: 'longTerm',
      label: 'Long-Term Goals',
      description: '3 roles to aspire to (6-12 months)',
      roles: [
        {
          id: '11',
          title: 'VP of Engineering',
          company: 'Tech Company K',
          matchPercentage: 45,
          category: 'longTerm',
          requiredSkills: [
            'Strategic Planning',
            'Team Leadership',
            'Technical Excellence',
            'Executive Communication',
          ],
          skillGaps: ['Strategic Planning', 'Executive Communication'],
          estimatedMonthsToReady: 12,
          salary: { min: 300000, max: 400000 },
        },
        {
          id: '12',
          title: 'CTO',
          company: 'Tech Company L',
          matchPercentage: 52,
          category: 'longTerm',
          requiredSkills: [
            'Architecture',
            'Leadership',
            'Business Acumen',
            'Vision Setting',
            'Team Building',
          ],
          skillGaps: ['Business Acumen', 'Vision Setting'],
          estimatedMonthsToReady: 18,
          salary: { min: 350000, max: 500000 },
        },
        {
          id: '13',
          title: 'Technical Director',
          company: 'Tech Company M',
          matchPercentage: 58,
          category: 'longTerm',
          requiredSkills: ['Architecture', 'Technical Strategy', 'Leadership', 'Mentoring'],
          skillGaps: ['Technical Strategy', 'Mentoring'],
          estimatedMonthsToReady: 10,
          salary: { min: 250000, max: 350000 },
        },
      ],
    },
  ],
  careerRoadmap: [
    {
      week: 1,
      milestone: 'Resume Optimization',
      description: 'Update resume with quantified metrics and impact statements',
      status: 'completed',
      estimatedHours: 8,
    },
    {
      week: 2,
      milestone: 'AWS Fundamentals',
      description: 'Complete AWS Certified Cloud Practitioner course',
      status: 'completed',
      skills: ['AWS'],
      estimatedHours: 20,
    },
    {
      week: 3,
      milestone: 'Docker Mastery',
      description: 'Learn Docker containerization and best practices',
      status: 'current',
      skills: ['Docker'],
      estimatedHours: 24,
    },
    {
      week: 4,
      milestone: 'Kubernetes Basics',
      description: 'Understand Kubernetes orchestration fundamentals',
      status: 'upcoming',
      skills: ['Kubernetes'],
      estimatedHours: 30,
    },
    {
      week: 5,
      milestone: 'System Design Deep Dive',
      description: 'Master advanced system design patterns',
      status: 'upcoming',
      estimatedHours: 25,
    },
    {
      week: 6,
      milestone: 'Go Programming',
      description: 'Learn Go for backend development',
      status: 'upcoming',
      skills: ['Go'],
      estimatedHours: 32,
    },
    {
      week: 7,
      milestone: 'Project Capstone',
      description: 'Build end-to-end project showcasing new skills',
      status: 'upcoming',
      estimatedHours: 40,
    },
    {
      week: 8,
      milestone: 'Interview Preparation',
      description: 'Prepare for senior-level technical interviews',
      status: 'upcoming',
      estimatedHours: 16,
    },
  ],
  quickActions: [
    {
      id: '1',
      title: 'Upload Resume',
      description: 'Upload a new resume version for analysis',
      icon: 'Upload',
      action: 'upload',
    },
    {
      id: '2',
      title: 'Analyze Job Description',
      description: 'Get insights on how you match a job posting',
      icon: 'Briefcase',
      action: 'analyze',
    },
    {
      id: '3',
      title: 'Continue Roadmap',
      description: 'Resume your career development plan',
      icon: 'MapPin',
      action: 'roadmap',
    },
    {
      id: '4',
      title: 'View Latest Analysis',
      description: 'See your most recent resume analysis',
      icon: 'BarChart3',
      action: 'analysis',
    },
  ],
};
